services:
  node:
    image: mcr.microsoft.com/devcontainers/typescript-node:0-20
    volumes:
      - ..:/app
    ports:
      - "3000:3000"
    command: sleep infinity  # Keep the container running for development
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
